language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
  app:
  run: rails db:migrate

env:
  global:
    secure: G2yKnVJMIrKytgUhRZygxu39/UM4pbPxcWLdpzaTxR0MOBtr+AwLVMDOwp4ov1HFF8v9LIy8hva2bMNyOz2ENA7XwkKvVMNaLBw1Q6VU124MhYn0COpD2ShyXszxAI/ABRkFfGUnTP0YSSEDgJWA7yWu5kI6hUC4PNatltvWGjs+8/phjAu7/+3ZxWAuW26E1A1pmFLS7PNEustXZr3C0Tb09NfzeUkGA2ZUoCcjTeSj1Hp4Fj4IKSbirGMeLANNn1gr8IbexxG/5Irt2UgI+sC5878HZxg8orsG3zRkz1I33RW5jD+Hr27rfIHyWwEMB6yrSCBBq75OdIfnk1foulhBGlH3VWJ6x9jWbrkMdhhMNUVWTzl0w/pcKOcVF/JdOyZxVZFjxRdnf6ehvaa9Ko7aalm+uaWI18Sr11lwod2k7o5LjPgfrs6DVRG/VLbVo2jp5d0rQ1KEeGAEdKQTmTQotlYdCDd+pnjfsmwST0f9/Rv++wtmMFH2K5KkZYOspcKVRN+5wBGkmBWSVyZQATNUaNpu+Ktfl+4PmUvAyUuMolVery21I+DmsaNOGzbSfNfq/cE3TFC+x6wz+w6mXcuDylHAfLNj3YsakbsakvZlIgLO+IdK8bBGzq/QCpPyEp0hYoZeYh1ZeortULTMjMlSmnjpgtgMStAbCUNFwXA=
